### ISSUE TITLE
Can't display the content of field

### ISSUE THREAD

**Issue by merksk8** [locomo/acf-field-buddypress-groups#2]
Hi,
When I include the code to see the information of fields from ACF it works, but when I do the same with the buddypress group field, it sends a number instead of the name of the group. For example if i choose the second group called ''Test Group'', the field sends ''2'' instead ''Test Group''.
How can I do this???

I've tried this:
<?php the_field($field_name, $post_id); ?>
and this:
<?php $field = get_field($field_name, $post_id, $format_value); ?>
Same result.
 Already tried to explore the code of your plugin looking for answers but i'm new in PHP and HTML so can't find a solution myself. 

And another little question, I hope you don't mind me to ask, this is really not important but wanted to ask if you thought about doing same plugin but for WP user frontend?
Thanks for your time, and great plugin.

**Comment by locomo** [comment]
the field stores the group ID of the buddypress group ... so if you needed the group name for example you could do something like this:

    $group_id = get_field( 'your_field_name' );
    $group = groups_get_group( array( 'group_id' => $group_id ) );
    echo $group->name;

hope that helps!

**Comment by merksk8** [comment]
yes thank you!!! 
easier than get_field ( 'your_field_name' ) is the field ( 'your_field_name' ) because the first one have more variables that in my case are not useful, anyway is perfectly working.
So really thanks for this and the quick answer, now I'm trying to understand a bit more acf, buddypress and wordpress and this helped me a bit to understand!! :)

**Comment by locomo** [comment]
hey, I was thinking about the issue you posted and I've updated the field to include a return_format option

now you can choose whether you want to return the Group ID(s)  OR the entire Group Object(s)

in your case if you choose Group Object then you can skip the step of having to call `groups_get_group`

https://github.com/locomo/acf-field-buddypress-groups/commit/8f56d797688d85d4aa561cdf0bbc9b1bacc9838b

**Comment by merksk8** [comment]
Wow, amazing ! =)
Thank you, i'm updating it, will be nice because was a bit tired to put the code everywhere where I wanted to show it! haha. Well, anyway it was good for me because I had to explore more about WP, BP and ACF, and I'm working on it to try to create my own functions and things like that =P.

Anyway, thanks!!!!

**Comment by merksk8** [comment]
well, how I said I'm new into this and can't really get it xD, but anyway maybe this helps a bit, I just want to help as I can!! If you don't like this or is really a disaster say it and i delete this comment haha.
As far as I can, maybe can be something like this?
=== Inside the function create_options( $field )===
`<tr class="field_option field_option_<?php echo $this->name; ?>">
	<td class="label">
		<label><?php _e("Return Format",'acf'); ?></label>
	</td>
	<td>
		<?php

		do_action('acf/create_field', array(
			'type'	=>	'radio',
			'name'	=>	'fields['.$key.'][format]',
			'value'	=>	$field['format'],
			'choices'	=>	array(
				1	=>	__("Group ID",'acf'),
				0	=>	__("Group Object",'acf'),
				2	=>  __("Group slug",'acf'),
				),
			'layout'	=>	'horizontal',
		));

		?>
	</td>
</tr>`

===================================================
Then I looked the example in the taxonomy.php, the taxonomy field of ACF by default that shows the same option, return object or ID and says this

=====default function format_value_for_api() for taxonomy field to use as a base ======
`function format_value_for_api( $value, $post_id, $field ) {
		
		// bail early if no value
		if( empty($value) ) {
			return $value;
		}
		// force value to array
		$value = acf_force_type_array( $value );
		// convert values to int
		$value = array_map('intval', $value);
		// load posts if needed
		**if( $field['return_format'] == 'object' ) {	
			// get posts
			$value = $this->get_terms( $value, $field["taxonomy"] );**
		}
		// convert back from array if neccessary
		if( $field['field_type'] == 'select' || $field['field_type'] == 'radio' ) {	
			$value = array_shift($value);	
		}
		// return
		return $value;
	}
`
I'm stuck here, I don't know how to do it, I hope this helps a bit while I continue looking for a solution for v4!! I'll be checking answers but I don't need it right now =).

How I said, thanks anyway!!

**Comment by locomo** [comment]
hey ..sorry, didn't realize you were using ACF 4 .. not sure if I can get to it today, but i'll try to update this soon to support ACF 4 

so in addition to group  ID and entire group object, you'd also like the option to return the group slug?

seems like just returning group object would be suitable here .. then you can use group->name and group->slug etc?

**Comment by merksk8** [comment]
don't worry, take your time!!
would be great to have the group slug, but once you have done the ''name'', then i will can learn how to do it for the slug, as I did when you said me how to do it through the groups_get_group, but if you implement it, would be amazing :)
Thank you!!

**Comment by locomo** [comment]
i updated the plugin to support ACF 4

would be great if you could test and confirm when you have a minute

cheers

**Comment by merksk8** [comment]
Not working for me, the ID works good as always but when I pick ''object'', it didn't work.
With the_field('myfield'); it returns the word ''array''.
With get_thefield('myfield'); it breaks the page from the point where is supposed to show the name of the group.

Tried couple of things, the first error I saw was **''groups_get_groups''** I think that the correct was **''groups_get_group'' as you told me before**, but anyway changing this doesn't work.
Another ''''error''''' I see, but I really don't know if it's an error, is the 'include'....I thought it had to be 'group_id', but changing it doesn't work anyway.

In this zone of text, why can't use only the variables $value, $field and $post_id? Because I tried to do this:

`
$group_id = $value;
$group = groups_get_groups(array(
		'group_id' => $group_id
	));
$value = $group->name;
`

and it's not working too, what I'm missing? Really, I'm trying to help but I'm new in all this code but I'm learning, I will keep testing for if I'm doing something wrong!
I appreciate the time that you spend on this, I will try to keep helping and at this time I'm using the old code that you told me on the pages.

**Comment by locomo** [comment]
i've updated the plugin and added some documentation for how to use it in your templates

in general 'the_field' won't work very well for this type of field .. its similar in some ways to the ACF Post Object field:
http://www.advancedcustomfields.com/resources/post-object/

anyway, check out the documentation in the readme and let me know if that helps

basically if you choose the 'group object'  for return format you'll get everything you need .. ie $group->name, $group->slug, etc etc
