### ISSUE TITLE
How to not select any group?

### ISSUE THREAD

**Issue by pmackay** [locomo/acf-field-buddypress-groups#4]
If I add this ACF field, it shows all the member groups but no blank option. So the first group is always selected. Is there any way to configure this so no group can be chosen?

Thanks in advance!

**Comment by locomo** [comment]
hey.. this custom field renders as an ACF Select field. The select field has an option called "allow_null". So somewhere before I call "do_action('acf/render_field/type=select', $field );" you would just need to update the $field array with the allow_null setting - i.e.

`$field['allow_null'] = true;`

i'll try to make an update soon that provides this an an optional setting, but in the meantime I think this should give you what you want

**Comment by locomo** [comment]
actually i just made the change .. when you have a chance could you pull down the new code and see if it works as expected?

**Comment by pmackay** [comment]
Yes, works great! Thanks for the rapid response! 

When do you push new updates out so they appear on WP.org?

**Comment by locomo** [comment]
hey .. glad it worked! This plugin isn't on wp.org so best thing to do is to probably to watch this project on git if you want to be kept apprised of updates

i'm not actively adding new features so the plugin doesn't change very frequently ... i do try to address any bugs that come up or make quick changes like your request
